version: "3.9"

services:
  node_ddd_skeleton:
    build: .
    restart: unless-stopped
    ports: 
      - "3000:3000"
    volumes:
      - ./package.json:/code/package.json
      - ./src:/code/src
    env_file: 
      - ./dev.env
    command: bash -c "npm run start:dev"
  redis_ddd_skeleton:
    image: redis:6.0.10-alpine
    container_name: redis_ddd_skeleton
    logging:
      driver: none
    ports:
      - 6379:6379
