version: "3.9"

networks:
  rabbitmq-prometheus:
  node_ddd_skeleton:
volumes:
  rabbitmq-prometheus_prometheus:
  rabbitmq-prometheus_grafana:

services:
  node_ddd_skeleton:
    build: .
    restart: unless-stopped
    networks:
      - "node_ddd_skeleton"
    ports: 
      - "3000:3000"
    volumes:
      - ./package.json:/code/package.json
      - ./src:/code/src
    env_file: 
      - ./dev.env
    command: bash -c "npm run start:dev"
    depends_on:
      - redis_ddd_skeleton
      - rabbitmq_ddd_skeleton
  redis_ddd_skeleton:
    image: redis:6.0.10-alpine
    container_name: redis_ddd_skeleton
    networks:
      - "node_ddd_skeleton"
    logging:
      driver: none
    ports:
      - 6379:6379
  rabbitmq_ddd_skeleton:
    container_name: rabbitmq_ddd_skeleton
    image: 'rabbitmq:3.8.9-management'
    networks:
      - "node_ddd_skeleton"
      - "rabbitmq-prometheus"
    restart: unless-stopped
    ports:
      - 5630:5672
      - 8090:15672
      - 15693:15692
    cap_add:
      - ALL
    environment:
      - RABBITMQ_DEFAULT_USER=ddd_skeleton
      - RABBITMQ_DEFAULT_PASS=ddd_sk3l3t0n
      - RABBITMQ_ERLANG_COOKIE=rabbitmq-prometheus
  grafana_ddd_skeleton:
    container_name: grafana
    image: grafana/grafana:7.3.2
    ports:
      - 4000:3000
    networks:
      - "rabbitmq-prometheus"
    volumes:
      - rabbitmq-prometheus_grafana:/var/lib/grafana
      - ./docker/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/rabbitmq.yaml
      - ./docker/grafana/datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - ./docker/grafana/dashboards:/dashboards
    environment:
      GF_INSTALL_PLUGINS: "flant-statusmap-panel,grafana-piechart-panel"
  prometheus_ddd_skeleton:
    # https://hub.docker.com/r/prom/prometheus/tags
    container_name: prometheus
    image: prom/prometheus:v2.22.1
    networks:
      - "rabbitmq-prometheus"
    ports:
      - "9090:9090"
    volumes:
      - rabbitmq-prometheus_prometheus:/prometheus
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
  node-exporter_ddd_skeleton:
    container_name: node-exporter
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    # https://hub.docker.com/r/prom/node-exporter/tags
    image: prom/node-exporter:v1.0.1
    networks:
      - "rabbitmq-prometheus"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
