name: "Continuous integration"
on:
  push:
      branches:
      - master
  pull_request:
      branches:
      - master

jobs:
  build:
    name: Check code quality and unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build API
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Run lint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint

      - name: Run unit tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test:unit
